### ISSUE TITLE
Descriptive error log

### ISSUE THREAD

**Issue by awstar** [Dash-Industry-Forum/Conformance-Software#123]
Would it be possible to have the error log provide links to the wiki articles that describe the error in detail,  and provide common cause or solutions?  The errors thrown are not easily searched, and the results often just refer to others asking the same question.  If the standard is so refined to understand where an error in conformance is, reporting in detail the violation in the spec should not be that hard.

**Comment by waqarz** [comment]
Can you please give an example from the error/log/screenshot what the issue is?

**Comment by awstar** [comment]
Here you go. 

 Some type of descriptive error in the log view, or at least links to the wiki would help people that are encoding their own content.  My guess the issues are with MP4Box and not so much the video encoder.  Its so hard to tell where the issue is when you are using 2-3 different apps to just get the conformance test.

![conformance-errors](https://cloud.githubusercontent.com/assets/5062916/13339178/ef0823f2-dbe3-11e5-85bc-797a3df74319.jpg)

**Comment by waqarz** [comment]
OK, this needs clarification. From DASH-conformance perspective, please only focus on errors, warning as almost irrelevant. So the issue to focus would only be the complaint about tkhd flags set to 0xF. This is a conformance issue according to ISO BMFF spec. If I see Section 8.3.2.3:

=================================
flags is a 24-bit integer with flags; the following values are defined:
Track_enabled: Indicates that the track is enabled. Flag value is 0x000001. A disabled track (the low bit is zero) is treated as if it were not present.
Track_in_movie: Indicates that the track is used in the presentation. Flag value is 0x000002.
Track_in_preview: Indicates that the track is used when previewing the presentation. Flag value is 0x000004.
=================================

This means the 4th bit should not be set as the case of your content.
