### ISSUE TITLE
Validator fail

### ISSUE THREAD

**Issue by richardbushell** [Dash-Industry-Forum/Conformance-Software#127]
Continuation from #124 which was closed.

Thanks, with the Online Validator all representations of both (video and audio) adaptation sets now pass (lovely green ticks), but we have other test files that still generate a final failure, e.g.:

https://living.video/MPD/test8.mpd

At the very last second before completing the validation we now get:
Cross-representation validation success (on audio) - green tick
Cross-representation validation error (on video) - red tick

There is no clickable log or any more information available as to why this might now fail this final check.

Don't know if this is related to the same error/fix.

Please advise asap please.

**Comment by waqarz** [comment]
We've given it a look. Its happening in the sense that the test set we are using have all indexed data, while this content does not have indexing. Can you provide such test vectors to us that we can host locally and include it in the testing. This will imporve the chances that your vectors are always supported by updates.

**Comment by richardbushell** [comment]
OK, can you fix the logic now from what you have now with this example.

I am happy to then supply whatever you need for future test vector testing. What do you need for testing? The original MP4s, the Fragmented MP4s, or just the segmented files and MPD? Did you have an FTP account, or a central email address to send the files via WeTransfer (or similar)?

**Comment by waqarz** [comment]
OK, diving very deep into the content reveals that this is a content issue. The moov box in, for example, representation id="video/5" contains a single edit with segmentDuration=54760, mediaTime=1024, mediaRate=1.0. The media timescale is 12800. This means play from 0.08 seconds till 4.278125 seconds. Now this makes roughly only the first couple of segments, and this means that for all the remaining segments, there are no presentable samples. However, the MPD declares segmentAlignment="true" for this adaptation set, while segments with no presentable samples cannot be aligned with other representations, hence this is a DASH conformance error.

**Comment by richardbushell** [comment]
@waqarz
Hmmm, thanks for taking a look. Can only think that our 3rd party packager's software update last week may have broken this. I'll have a look myself then contact them if there's a new bug. Just a quick question, I can see that the MovieBox (MOOV) box has TimeScale 1000, does the Edit List (ELST) ignore that and always use 12800 as the base anyway even though it's within the MOOV container?

**Comment by richardbushell** [comment]
A very quick Google Search threw up:
https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html
(yes, this relates to QTFF so may be different for CFF):-
An edit list table entry contains the following elements.
Track duration: A 32-bit integer that specifies the duration of this edit segment in units of the movie’s time scale.
Media time: A 32-bit integer containing the starting time within the media of this edit segment (in media timescale units). If this field is set to –1, it is an empty edit. The last edit in a track should never be an empty edit. Any difference between the movie’s duration and the track’s duration is expressed as an implicit empty edit.
Media rate: A 32-bit fixed-point number that specifies the relative rate at which to play the media corresponding to this edit segment. This rate value cannot be 0 or negative.
***
SO, should the Duration use TimeScale 1000 (rather than 12800)?
With the MediaTime using 12800.
Am I reading this right?

**Comment by richardbushell** [comment]
Now had chance to double-check. Edit List Duration is in Movie TimeScale of 1000 (not Media TimeScale of 12800). If the Validator uses the wrong TimeScale for Edit List Duration then this should be a very simple fix.

Or, it is something else causing the reported failure.

**Comment by waqarz** [comment]
So this issue is then unrelated to https://github.com/Dash-Industry-Forum/Conformance-Software/issues/124? I check the details.

**Comment by waqarz** [comment]
This issue is address in https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/23 and is online.

**Comment by richardbushell** [comment]
@waqarz - thanks so much for fixing this so prompty, really appreciate it!
(I am so relieved that it isn't the media).
Yes, please do keep test8 in the future tests.
Do you need anything else from me?

**Comment by waqarz** [comment]
We have included the vector in our regression test list: https://github.com/Dash-Industry-Forum/Conformance-Software/blob/master/Test/DefaultVectorList.txt , hope that the URLs stay alive then this is included in our testing.
