### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by RavikiranMuniraj** [Dash-Industry-Forum/Conformance-Software#129]
Hi

When i try to validate the sample mpd file, I am getting "Wrong"(X) icon on "DASH Validator" tool, which is highlighted in red box on below snap
![capture1](https://cloud.githubusercontent.com/assets/17801979/13724641/5980b8ae-e8b2-11e5-95d5-1c62bee24e6c.JPG)

please refer the "mpd error log" file content below for this issue.
![capture2](https://cloud.githubusercontent.com/assets/17801979/13724651/8d6b346e-e8b2-11e5-9e8f-cab322bcb64e.JPG)

Could you please give the solution for this issue?

Thanks & Regards,
Ravikiran M

**Comment by waqarz** [comment]
Are you trying to run it on your own machine? If so, delete the contents of build directory in mpdvalidator.

**Comment by RavikiranMuniraj** [comment]
Hi waqarz,

Thanks for your reply!

Yes. I am trying to run mpd validator on my own system. But there is no directory with the name "build" in mpdvalidator. please refer the below pic.
![capture3](https://cloud.githubusercontent.com/assets/17801979/13729864/2073e744-e965-11e5-8256-141b1fc57d27.JPG)

please confirm, which file/directory i need to edit or what to edit.

Thanks & Regards,
Ravikiran M

**Comment by waqarz** [comment]
Delete all the contents of bin directory.

Also support for Windows is dated, try with Linux via Apache server (PHP, curl support required)
