### ISSUE TITLE
DASH Validator doesn't understand Role or SupplementalProperty elements

### ISSUE THREAD

**Issue by juzzlin** [Dash-Industry-Forum/Conformance-Software#135]
```<Role schemeIdUri="urn:mpeg:dash:stereoid:2011" value="r0"/>```

Gives error:

```Line:Col[27:73]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'Role'. One of '{"urn:mpeg:dash:schema:mpd:2011":Representation}' is expected.```

Same thing with SupplementalProperty elements.

**Comment by waqarz** [comment]
Please provide a sample to test this.

**Comment by juzzlin** [comment]
[stream.mpd.txt](https://github.com/Dash-Industry-Forum/Conformance-Software/files/225697/stream.mpd.txt)

**Comment by juzzlin** [comment]
The validator gives error of the SupplementalProperty elements. If I remove those it gives errors about the following Role elements.

**Comment by waqarz** [comment]
Have you checked if SupplementalProperty element is allowed within an AdaptationSet as in this MPD?

**Comment by juzzlin** [comment]
Well, an example in ISO 23009-1:

```<Period>
<!-- Panorama Video -->
<AdaptationSet segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
    <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
    <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="0,0,0,3,3,3,3"/>
...
```

**Comment by juzzlin** [comment]
The problem seems to be the fact the DASH XSD schema specifies a certain order for elements. I don't find that particularly funny, because the XML lib I'm using to post-process MPD files doesn't support that.

**Comment by mcflyuk** [comment]
Was about to raise an issue regarding this but looks like it has already been covered to a certain extent.

DVB DASH requires descriptor information for HDR video at an AdaptationSet level:

> DVB-DASH, 5.2.5
> Information on colour primaries, matrix coefficients and transfer characteristics may be signalled using
> EssentialProperty or SupplementalProperty descriptors applied to an AdaptationSet as defined in this clause
> ...
> This signalling shall only be applied at the AdaptationSet level...

For HLG10 video:

```
<EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:ColourPrimaries" value="9"/>
<EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:MatrixCoefficients" value="9"/>
<EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:TransferCharacteristics" value="14"/>
<SupplementalProperty schemeIdUri="urn:mpeg:mpegB:cicp:TransferCharacteristics" value="18"/>
```

For PQ10 video:
```
<EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:ColourPrimaries" value="9"/>
<EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:MatrixCoefficients" value="9"/>
<EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:TransferCharacteristics" value="16"/>
```

MPD files with these descriptors at AdaptationSet level will produce an error in the validator.

Example file for testing attached:
[DASH-VRESHFR0010.zip](https://github.com/Dash-Industry-Forum/Conformance-Software/files/2558506/DASH-VRESHFR0010.zip)

**Comment by mcflyuk** [comment]
Further investigation found that the MPD will pass the validator if the EssentialProperty/SupplementalProperty descriptors are positioned first in the AdaptationSet.

**Comment by waqarz** [comment]
@mcflyuk this seems to conflict with DASH MPD schema, is there a specific issue to be addressed here?

**Comment by mcflyuk** [comment]
> @mcflyuk this seems to conflict with DASH MPD schema, is there a specific issue to be addressed here?

Having had the additional information shared with me about the positioning of the EssentialProperty/SupplementalProperty descriptors, I don't think there's an issue if I change the ordering.
