### ISSUE TITLE
Question on USing your server with Python code

### ISSUE THREAD

**Issue by AyliD** [Dash-Industry-Forum/Conformance-Software#141]
Hi,

I want to automate the validation of our Dash manifests, and will be happy to use your server.
Im getting 500 Internal Server error and cannot trouble shoot it.

My code is:

----------------------------------------------------------------------------------------------------------------------
import os 
import urllib2
import json

def upload_creative(sessionid, file_path, url):
    """"""
    boundary = "WebKitFormBoundaryWY486EIcZJtOf9J5"
    file_name = os.path.basename(file_path)
    parts = []

    # Set File part.
    parts.append('--' + boundary)
    parts.append('Content-Disposition: form-data; name="afile"; filename="%s"' % file_name)
    parts.append('')
    parts.append('Content-Type: %s' % 'application/octet-stream')
    parts.append(open(file_path, 'r').read())

    # Set session ID part.
    parts.append('--' + boundary)
    parts.append('Content-Disposition: form-data; name="sessionid"')
    parts.append('')
    parts.append(str(sessionid))

    # Set foldername part.
    parts.append('--' + boundary)
    parts.append('Content-Disposition: form-data; name="foldername"')
    parts.append('')
    parts.append("id9103678202")

    # Set urlcode part.
    parts.append('--' + boundary)
    parts.append('Content-Disposition: form-data; name="urlcode"')
    parts.append('')
    parts.append("%s" % ["upload","mpdvalidator",0])

    # End
    parts.append('--' + boundary + '--')
    parts.append('')
    

    body = '\r\n'.join(parts)

    headers = {'content-type': 'multipart/form-data; boundary=' + boundary,
    'Connection': 'keep-alive',
    'Accept': '*/*',
    'X-Requested-With': 'XMLHttpRequest',
    'Referer': url.replace("process.php","conformancetest.php"),
    'Cache-Control': 'no-cache',
    'Pragma': 'no-cache',
    'Accept-Encoding': 'gzip, deflate',
    'Cookie': 'id498243=cckromc94nv0971cbbvlnl33d1; id581240=mkdce37dqn38kljmusj5eoj9f4; PHPSESSID=5qm5trl7dujno6c9fgihaqiab2',
    'Accept-Language': 'en-US,en;q=0.8'
    }
    
    req = urllib2.Request(url, headers=headers, data=body)
    print "SWP req:\n%s\n%s\n" % (req.headers, req.data)
    print dir(req)
    res = urllib2.urlopen(req)
    print dir(res)
    return json.loads(res.read())

url = "http://54.72.87.160/conformance/current/webfe/process.php"
upload_creative("id581240", "/home/eayereg/Desktop/Manifest", url)

**Comment by joywelt** [comment]
Hi @AyliD , I think the 500 error is caused by your headers setting. There is also a problem with your urllib2.Request call.

Please change "req = urllib2.Request(url, headers=headers, data=body)"
to "req = urllib2.Request(url, body)"

When you're sure about your settings, then use "req = urllib2.Request(url, body, headers)"

**Comment by joywelt** [comment]
Hi @AyliD , I think the 500 error is caused by your headers settings. 
Your settings for "Cookie" introduced this problem, and settings for "Accept-Encoding" made the results not readable.

**Comment by AyliD** [comment]
@joywelt , Can you recommend me which headers are mandatory?

**Comment by AyliD** [comment]
@joywelt  thanks for the quick response.

I have changed my code to be much simpler, i dont getthe Internal Error but the report created by the tool is:

http://54.72.87.160/conformance/current/webfe/temp/ayliwashere/mpdreport.txt

0Buildfile: build.xml does not exist!
Build failed

Code is:

def upload2(sessionid, file_path, url):

    import requests
    file_name = os.path.basename(file_path)
    files = {'afile': (file_name, open(file_path, 'rb')), 'sessionid': (None, sessionid),
              'foldername': (None, 'ayliwashere'), 'urlcode': (None, "%s" % (["upload","mpdvalidator",0]))}
   
    a = requests.post(url, files=files)
    print "Request %s\n" % ((a.request.body))
    print "Headers %s\n" % a.request.headers
    print "Text %s \n" % a.text

**Comment by waqarz** [comment]
@joywelt how could a folder such as "webfe/temp/ayliwashere/" be allowed to created?

**Comment by joywelt** [comment]
@waqarz She specified the folder name by 
`'foldername': (None, 'ayliwashere')`,
so the temp folder has a user defined name instead of a random ID.

**Comment by joywelt** [comment]
@AyliD I cannot open your link. Is your problem solved?

**Comment by AyliD** [comment]
Guys, thank you so much for your help! all working!

import requests
import random
import math

url = 'http://54.72.87.160/conformance/current/webfe/process.php'
file_path = "/home/eayereg/Desktop/Manifest_NOK"
files = {'afile': (file_path, open(file_path, 'r').read(), 'text/xml')}
dir_id = 'id%d' % math.floor((random.random() * 10000000000) + 1)
r = requests.post(url, data={'foldername': dir_id, 'sessionid': '"id491641"',
                             'urlcode': '["upload","mpdvalidator",0]'}, files=files)
print r.status_code
print r.request.body
print r.text

**Comment by waqarz** [comment]
@joywelt will 'foldername': (None, 'ayliwashere') work with
- Our "garbage collection" i.e. will be deleted properly in time.
- Would this allow relative paths, e.g. someone could command 'foldername': (None, '../../xyz')? this will be a security issue, we have restrict this

**Comment by joywelt** [comment]
@waqarz I tested regarding your questions.
1. yes, the "garbage collection" will delete all old folders no matter what their names are.
2. unfortunately yes. We should fix it.

**Comment by joywelt** [comment]
@waqarz the issue is fixed in PR #140. We might also think about changing the writing permission of our server (i.e. all read-only except for the temp folder).
