### ISSUE TITLE
Download results as zip

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Conformance-Software#142]
I would like a feature to download the validation results as a zip file - currently they appear to be deleted quite fast, so while I am investigating some errors, I suddenly find the logs 404ing on me.

**Comment by waqarz** [comment]
@sandersaares right now the garbage collection seems to be too aggressive, I learnt that its 5 minutes. To start with we make it 30 minutes.

**Comment by joywelt** [comment]
@sandersaares I changed the time for deleting the results to 30min now. If you are using the service locally, please update with git. We will also update our online service soon.

**Comment by sandersaares** [comment]
Thanks for fast action!

**Comment by waqarz** [comment]
Updated online, please reopen if this needs further addressing.
