### ISSUE TITLE
Several UI issues, especially when using mpdurl query parameter

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Software#160]
See the circled items, the content is on the local server
![image](https://cloud.githubusercontent.com/assets/3089913/19157857/f3895398-8be6-11e6-9e60-4fa52e21d5f4.png)

**Comment by waqarz** [comment]
On the first item, it is asking to check for dynamic timing, while the MPD is static

**Comment by joywelt** [comment]
Fixed in #170

**Comment by joywelt** [comment]
Close now. Reopen if in case of further problem.
![10182](https://cloud.githubusercontent.com/assets/5159952/19480550/0def3fc8-954b-11e6-9c8b-bcb35fd79b3a.jpg)

**Comment by joywelt** [comment]
Reopen because the fix for this UI issue caused a problem for MPD conformance only check(it doesn't show the results).

**Comment by joywelt** [comment]
Further fix in #179 289edc0
