### ISSUE TITLE
Crash on MPD

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Software#161]
On the MPD on local server, it seems segment conformance crashes on some of the representations (no log found for rep 1, 2): http://10.4.247.98/Content/ToS4k/DASHed/1_0/MultiRate.mpd

**Comment by joywelt** [comment]
Could you please check again with http://10.4.247.98/Content/ToS4k/DASHed/TestCasesUHD/2b/4/MultiRate.mpd?
For me it shows the error log for rep 1 (cross representation validation error)

> Cross representation checks for adaptation set with id "":
Error: Number of tracks logged 0 for representation with id "1" not equal to the number of indexed tracks 1 for representation id "3"
Error: Number of tracks logged 0 for representation with id "1" not equal to the number of indexed tracks 1 for representation id "4"
Error: Number of tracks logged 0 for representation with id "1" not equal to the number of indexed tracks 1 for representation id "5"
Error: Number of tracks logged 0 for representation with id "2" not equal to the number of indexed tracks 1 for representation id "3"
Error: Number of tracks logged 0 for representation with id "2" not equal to the number of indexed tracks 1 for representation id "4"
Error: Number of tracks logged 0 for representation with id "2" not equal to the number of indexed tracks 1 for representation id "5"
Checks completed.

There is no error shown for rep 2.
![1017](https://cloud.githubusercontent.com/assets/5159952/19433551/84b98234-9461-11e6-82b1-46d5107df415.jpg)

**Comment by joywelt** [comment]
I checked the backend and figured out that the log files are empty because error occurs. 
Fixed in #170 
![1018](https://cloud.githubusercontent.com/assets/5159952/19470502/1187432c-9520-11e6-994c-9be0dda19b71.jpg)
![10182](https://cloud.githubusercontent.com/assets/5159952/19470501/1181258c-9520-11e6-8e05-c7e9b98e9147.jpg)

**Comment by waqarz** [comment]
Why does it says Adap "0", it should be Adaptation set 1, rep 1

**Comment by joywelt** [comment]
@waqarz This index corresponds to the name of log files. I could also change it to starting from Adaptation set 1, rep 1

**Comment by joywelt** [comment]
Modified the index. Close the issue now. Reopen if there's a problem.
![10182](https://cloud.githubusercontent.com/assets/5159952/19488346/c38078e6-9566-11e6-8b3b-d8ff706fb452.jpg)
