### ISSUE TITLE
Inconsistent Segment Naming

### ISSUE THREAD

**Issue by tlohmar** [Dash-Industry-Forum/Conformance-Software#167]
A segment with a certain url is sometime references as “Leaf count X” and sometimes as “Media Segment X”

Example:

**Comment by waqarz** [comment]
A leaf subsegment is defined in ISO BMFF spec.

**Comment by tlohmar** [comment]
The issue was not about the name "leaf subsegment", but the inconsistent usage of "leaf count" and "Media Segment". There seem to be two names for the same things.

Further, it would be good to identify the Segment Url from the bug report, to enable manual checking of the identified error.

**Comment by waqarz** [comment]
> There seem to be two names for the same things.

If a segment has a single sub-segment which refers to media, then in this case, this segment = subsegment = leaf subsegment, so in this case it is the name of the same thing.
