### ISSUE TITLE
Implementation of Segment template, specifically replacing $Number$ is not complete

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Software#168]
Make it conforming to the standard
- Specially, using formatting specifiers, e.g. DASH standard allows $Number%05d$

**Comment by waqarz** [comment]
Check the code from line 375 in https://github.com/Dash-Industry-Forum/Conformance-Software/blob/master/webfe/mpdprocessing.php , it is clearly broken.

**Comment by joywelt** [comment]
Fixed in #172 . Close the issue now. Reopen in case of other problems
