### ISSUE TITLE
Test framework for MPD chaining vectors

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Software#198]
Test framework should be modified to accommodate MPD chaining featured vectors as it requires separate instance/session/window for conformance test.

**Comment by waqarz** [comment]
We are OK if the test framework ignores the results of "chained to" MPD, is this the current behavior?

**Comment by niteeshbhat** [comment]
Yes, there are two kinds of behaviour currently. 
1. If the MPD chaining vector is the last vector to be tested, then chained-to MPD results are ignored.
2. If not 1, chained-to MPD results replaces the next vectors' results and somewhat disturbs test framework sequence.

**Comment by waqarz** [comment]
OK, the chained to MPD results must be ignored, this should be incorporated in the test framework.
