### ISSUE TITLE
Visitor log- MPD processing completion log

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Software#223]
MPD processing completion time to be added in visitor log

**Comment by waqarz** [comment]
The CPU usage spiked again to 100:

- Top was showing around 58%; still the log file was showing 18%
- Even Top cannot be relied upon for EC2 instance performance monitoring: https://forums.aws.amazon.com/thread.jspa?threadID=67697 ; we have to use some other way, e.g. Cloudwatch 
- The log (saved locally) shows again several tests run by a single user in quick succession that resulted in very high CPU usage that persisted and strangely again the name of the temp folder was always the same. These tests do not show an end time, though the folders were already deleted when I checked, i.e. the CPU was still high although there was no temp folder with a running test.

**Comment by niteeshbhat** [comment]
I observed the log file and working on it now.
Some more clarifications on above mentioned points.

- Log file shows CPU usage as normalized. So a value of 1 means 100%. When it crossed 1, it went  soon to 18 in the above case of a single user.
- If the entered URL itself is wrong, there won't be any resources allocated (in temp folder), so no logging for it.

**Comment by waqarz** [comment]
- We need to document with the source is how sessions are cleaned: timeouts; we expect multiple cases of doing this
- Check the document of the command line interface (there we gave possibility of manual folder name): check this; we should disable manual folder name if its allowed by API. Add this documentation to the main document also.
- Move things to a new doc folder.

**Comment by niteeshbhat** [comment]
Among above mentioned points,, 1 and 3 done.
2 is open in #228 
Hence closing this issue.
