### ISSUE TITLE
Performance issues/ Optimization of conformance software

### ISSUE THREAD

**Issue by AdithyanIlangovan** [Dash-Industry-Forum/Conformance-Software#241]
As a first step in optimising the conformance software, we profile the software to identify how fast/slow it is running w.r.t different test vectors.

Three cases are run. 

1. With publicly available [conformance software](http://dashif.org/conformance.html)
2. The same conformance setup in a local machine.
3. The publicly available Klagenfurt university [conformance software](http://www-itec.uni-klu.ac.at/dash/?page_id=605)

The time take to compute the conformance is tabulated below. All of the test vectors conform successfully (MPD conformance only!). All time are in seconds.

TestURL | Type | Server machine | Local machine | Klagenfurt
-- | -- | -- | -- | --
https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd | Static | 10.05 | 2 | 4.05
http://vm2.dashif.org/livesim-dev/periods_60/xlink_30/insertad_1/testpic_2s/Manifest.mpd | Dynamic | 8 | 3 | 3.5
http://dash.akamaized.net/dash264/TestCasesUHD/2b/11/MultiRate.mpd7 | Static | 7 | 2 | 2.9
http://download.tsi.telecom-paristech.fr/gpac/dataset/dash/uhd/dashevc-ondemand-2s/dashevc-ondemand-2s-p60.mpd | Static | 7 | 1.5 | 2.2

)

Strangely the same software in EC2 instance runs much slower than running in a local machine. Identify potential sources of error. 

The promising part is the performance in local machine is faster than the publicly available klangefurt conformance software.

Early thoughts:
- Is EC2 instance somehow restricting the performance?
- Try the ant to java fix recommended by Waqar. See how much performance gain?
- Recompliliation of programs creating/time?

**Comment by waqarz** [comment]
Lets only apply the fix I proposed for now; by removing ANT and directly running java. I have seen that the main bottleneck is running the javacode itself on the EC2 so we dont have too much improvement possibility at this point in time. Lets pause this issue then.

**Comment by AdithyanIlangovan** [comment]
Okay. I will update the ANT to JAVA line you proposed earlier. To see how much it improves the performance.

**Comment by AdithyanIlangovan** [comment]
Just I add @waqarz 's proposed fix here for the sake of completion. 

When you work on it change webfe/mpdvalidation.php line 24:
Change
'''
$mpdvalidator = syscall("ant run -Dinput=\"" . $url_array[0] . "\" -Dresolved=" . $url_array[3] . "/resolved.xml" . " -Dschema=schemas/DASH-MPD.xsd"); //run mpd validator
'''
To
'''
$mpdvalidator = syscall('java -cp "saxon9.jar:saxon9-dom.jar:xercesImpl.jar:bin" Validator ' . $url_array[0] . " " . $url_array[3] . "/resolved.xml schemas/DASH-MPD.xsd");
'''
This runs the validator directly from java instead of running ant which checks compilation etc. and makes it already faster, needs to be tested a bit more.

**Comment by waqarz** [comment]
>  I will update the ANT to JAVA line you proposed earlier. To see how much it improves the performance.

It gives significant improvement on a local machine but not so much on EC2 unfortunately... still worthwhile to use. So the gap in Klagenfurt vs. EC2 should be server dependent

**Comment by AdithyanIlangovan** [comment]
Improvement fix provided in PR #242 !

The improvement with ANT fix seems to be substantial, it already provides 25%-30% reducing in computation time.

TestURL | Type | Server machine | Server machine -   ANT fix | Local machine | Klagenfurt
-- | -- | -- | -- | -- | --
https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd | Static | 10.05 | 7 | 2 | 4.05
http://vm2.dashif.org/livesim-dev/periods_60/xlink_30/insertad_1/testpic_2s/Manifest.mpd | Dynamic | 8 | 6 | 3 | 3.5
http://dash.akamaized.net/dash264/TestCasesUHD/2b/11/MultiRate.mpd7 | Static | 7 | 5 | 2 | 2.9
http://download.tsi.telecom-paristech.fr/gpac/dataset/dash/uhd/dashevc-ondemand-2s/dashevc-ondemand-2s-p60.mpd | Static | 7 | 5 | 1.5 | 2.2
  |   |   |   |   |  

Just some things to keep in mind

- The time logging is currently done in the order of seconds. 1, 2, 3, 4 seconds. So if we want to measure much more precisely we should increase the precision of logging. This would decrease the quantization error and we can say much more precisely how much it reduces.

- I am mostly sure that this reduction in time is due to ANT build to JAVA fix. But anyways just to be sure we need to run the same experiment again to verify whether the results are repeatable. Sometime EC2 farms have more resources than before, just to isolate that this was not the cause for performance reduction.
