### ISSUE TITLE
Feature list is blank

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Conformance-Software#254]
If I test the following mpd

http://dash.akamaized.net/dash264/CTA/imsc1/IT1-20171027_dash.mpd

it passes all conformance tests and a link to a "feature list" is generated in the results page. Clicking that link opens a new page which is blank and contains no feature list.

Test environment is FF-57 on Mac OSX. I have duplicated behavior on Chrome 62.

**Comment by waqarz** [comment]
@niteeshbhat please check; as I run it now I could see the feature list in Chrome; however one of the representations could not be validated. Please check throughly

**Comment by waqarz** [comment]
@wilaw we could not regenerate this issue here; one similar effect observed is if the list is not accessed for 30 minutes and the session expires then you get a not found... but this must be something different. Could it be that its processing delay (should not take more than 1-2 seconds). Can you maybe send a screenshot) (being a blankpage it's a bit ironic I admit :)

**Comment by waqarz** [comment]
b.t.w. we did find one issue with processing of ttml content related to this MPD fixed in this PR: https://github.com/Dash-Industry-Forum/Conformance-Software/pull/255

**Comment by wilaw** [comment]
Here are some screenshots, on both FF and Chrome

![screen shot 2017-12-11 at 8 41 00 am](https://user-images.githubusercontent.com/2762250/33842360-2a2799d0-de4f-11e7-9d1c-a1f97ad4440c.png)
![screen shot 2017-12-07 at 2 34 52 pm](https://user-images.githubusercontent.com/2762250/33842361-2a40c0b8-de4f-11e7-9724-7c0c427702ee.png)

**Comment by waqarz** [comment]
Thanks @wilaw 
@niteeshbhat I tried to access the page while it was still on the server and I also got the blank page. The bug is when you run MPD only conformance test. When you test segments the feature table appears. If not (if you run MPD only test) the page is blank.

**Comment by niteeshbhat** [comment]
@waqarz  Thank you very much. 
I fixed the issue for MPD-only conformance. 
Now featuretable is visible for both conformances.
Fixed in #256 . Tested. Closing this issue now.
