### ISSUE TITLE
MPD Validation failure 

### ISSUE THREAD

**Issue by kqyang** [Dash-Industry-Forum/Conformance-Software#282]
I am seeing validation failures when when trying to validate my mpd (https://storage.googleapis.com/wvtemp/kqyang/mp3/bunny_live.mpd) at http://dashif.org/conformance.html.

Here is the reported errors:

ImageDescription name must be ''
### Buffer underrun conformance error: first (and only one reported here) for sample 30 of run 1 of track fragment 1 of fragment 2 of track id 1 (sample absolute file offset 875192, fragment absolute file offset 683297, bandwidth: 548363)

Can someone explain what the problems are? It isn't very clear from the error message.

It looks like the error comes from the binary: https://github.com/Dash-Industry-Forum/Conformance-Software/blob/master/webfe/ValidateMP4.exe. Is the source available anywhere?

Thanks.

**Comment by waqarz** [comment]
The error is printed for stsd atom, reserved 1 bits are not 1. Please check the stsd atom

**Comment by kqyang** [comment]
Can you point to me which bit is the tool referring to? I don't see a "reserved = 1" one bit in stsd nor SampleEntry definitions.

``` cc
aligned(8) abstract class SampleEntry (unsigned int(32) format) extends Box(format){
  const unsigned int(8)[6] reserved = 0;
  unsigned int(16) data_reference_index;
}

aligned(8) class SampleDescriptionBox (unsigned int(32) handler_type) extends FullBox('stsd', version, 0)  {
  int i ;
  unsigned int(32) entry_count;
  for (i = 1 ; i <= entry_count ; i++){
    SampleEntry(); // an instance of a class derived from SampleEntry
  }
}

class VisualSampleEntry(codingname) extends SampleEntry (codingname){
  unsigned int(16) pre_defined = 0;
  const unsigned int(16) reserved = 0;
  unsigned int(32)[3] pre_defined = 0;
  unsigned int(16) width;
  unsigned int(16) height;
  template unsigned int(32) horizresolution = 0x00480000; // 72 dpi
  template unsigned int(32) vertresolution = 0x00480000; // 72 dpi
  const unsigned int(32) reserved = 0;
  template unsigned int(16) frame_count = 1;
  string[32] compressorname;
  template unsigned int(16) depth = 0x0018;
  int(16) pre_defined = -1;
  // other boxes from derived specifications
  CleanApertureBox clap; // optional
  PixelAspectRatioBox pasp; // optional
}

class AudioSampleEntry(codingname) extends SampleEntry (codingname){
  const unsigned int(32)[2] reserved = 0;
  template unsigned int(16) channelcount = 2;
  template unsigned int(16) samplesize = 16;
  unsigned int(16) pre_defined = 0;
  const unsigned int(16) reserved = 0 ;
  template unsigned int(32) samplerate = { default samplerate of media}<<16;
  ChannelLayout();
  // we permit any number of DownMix or DRC boxes:
  DownMixInstructions() [];
  DRCCoefficientsBasic() [];
  DRCInstructionsBasic() [];
  DRCCoefficientsUniDRC() [];
  DRCInstructionsUniDRC() [];
  Box (); // further boxes as needed
}
```

**Comment by niteeshbhat** [comment]
The binary source files are in this repository
https://github.com/Dash-Industry-Forum/Conformance-and-reference-source

The cause for this error is in the AVCConfigRecord, line number 1792 or 1804 in the file 
https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/blob/master/conformance/ISOSegmentValidator/public/src/ValidateBitStreams.cpp

This is triggered while validating AVC visual sample entry. (The AVCConfigRecord implementation follows guidelines from the AVC standard)

**Comment by kqyang** [comment]
I see. Thanks for the information. It will be easier to troubleshoot if the tool can mention that it is seeing something expected in AVCConfigRecord.
