### ISSUE TITLE
Mode of Use

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Software#289]
T2
Current status: Web based tool which validates all the profiles present in the MPD.

ToDo:  User selection of profiles to check conformance against.
User can select either HbbTV or DVB or both , and then the given test content is validated against the selected profiles.

**Comment by niteeshbhat** [comment]
PR merged here:
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/1

**Comment by eceozturk** [comment]
Feature-based reporting PR merged here:
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/30
