### ISSUE TITLE
Segments validation

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Software#293]
T6
	Check that there is no multiplexed A/V
	Check that other specific segment constraints from the HbbTV 1.5 and DVB DASH (and referenced) specifications are correctly observed.
	Report (error) if the segments include features that are not required by the profile being validated against
•	Eg. Those aspects of the sidx box that are profiled out of DVB-DASH
	Check sidx information is correct/valid
	Are the segment sizes (in bytes) and duration consistent with the representations bitrate? (report min / max / average / (Spread?))
	Are the start times within the segments consistent with the timing indicated by the MPD (including @presentationTimeOffset, if any)?
	Is the timing within the segments of a Representation such that there are no gaps?

**Comment by niteeshbhat** [comment]
Need guidance in implementing this, related to init seg but under Adaptation set E.3.2 HbbTV
"For video Rep, width and height values in tkhd  shall have the nominal display size in square pixels after decoding, AVC cropping and rescaling".

**Comment by eceozturk** [comment]
For the check "Report (error) if the segments include features that are not required by the profile being validated against", implementation done is the following:
- There shall be only one sidx box for on-demand profile according to DV-DASH doumentation
- In case of dynamic MPD with HbbTV profile, there shall be more than one segments.

**Comment by eceozturk** [comment]
For the check "Are the start times within the segments consitent with the timing indicated by the MPD":
- Used formula is Period@start + PTO = baseMediaDecodeTime + earlieastCompositionTime - mediaTime
- The consistency check for dynamic type MPDs are left to be implemented in the dynamic service validation software tool.

**Comment by niteeshbhat** [comment]
PRs merged 
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/26
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/27
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/29
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/32
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/33
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/34
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/35
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/37
