### ISSUE TITLE
DVB DASH specifics

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Software#306]
T19:
ToDos:
o	Frame rates should be part of families in Section 10.4 and that the frame rates are /2 or /4 or the one in section 10.4 (LOW)
o	There should be a check for content offering with multiple periods (10.5.2) (HIGH)
o	Base URLs (section 10.8) should be validated as these are not part of DASH-IF (HIGH)
o	MPD Anchors should be considered to be part of the checks (LOW)
o	Verifying the DVB Metric Reporting Mechanism should also be considered (LOW)

Exception: BaseURL checks are targeted for DASH player.

**Comment by eceozturk** [comment]
- Frame rates are only implemented according to table in 10.4. The second statement "that the frame rates are /2 or /4 or the one in section 10.4" is ambiguous, therefore it is left for further clarification if needed. The related PR: 
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/19

- Multi-period 10.5.2 is implemented. Related PRs: https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/83
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/84 

- Base URL in Section 10.8 is only targeted for players.

- MPD anchors are implemented only for syntactical and logical checks. Related PR:
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/85

- DVB Metric Reporting Mechanism checks are implemented. Related PR:
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/86
