### ISSUE TITLE
Low level child element replacing higher child element

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Software#340]
For example: when segment template  is present in AdaptationSet and Rep, then only the latter is considered in dynamic validator due to which attributes mentioned in the higher level gets lost.

If attributes are repeated, then replacing is fine. Otherwise merging and keeping all attributes is necessary.

**Comment by eceozturk** [comment]
Fix is provided by PR: https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/60
