### ISSUE TITLE
dashif.org/conformance.html app broken?

### ISSUE THREAD

**Issue by Murmur** [Dash-Industry-Forum/Conformance-Software#351]
Web application 
http://dashif.org/conformance.html

Is this application broken, it seems to do nothing. Firefox/F12/Console displayes this error over and over.  I tried several mpd url addresses.
```
ML Parsing Error: no root element found
Location: http://54.72.87.160/conformance/current/webfe/temp/id3332375210/progress.xml?1523446902328
Line Number 1, Column 1:
```

**Comment by waqarz** [comment]
@niteeshbhat please check, something is broke and it must be a very recent regresseion

**Comment by eceozturk** [comment]
Restarted the Apache server and now it is working.

**Comment by Murmur** [comment]
Check, working now.
