### ISSUE TITLE
Validator test doesn't complete.  Can't find progress.xml.

### ISSUE THREAD

**Issue by pingu0201** [Dash-Industry-Forum/Conformance-Software#377]
Using the web-based front-end, my test run doesn't complete.  I see constant messages like this:

conformancetest.php:1166 Failed to load resource: the server responded with a status of 404 (Not Found)

And also these in the HTTP response:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /conformance/current/webfe/temp/id4691204910/progress.xml was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at conformance.dashif.org Port 443</address>
</body></html>

If I select MPD Conformance-only, it works fine.

I'm new to this tool and could easily be doing something wrong.  Please let me know what info I can provide.  Also, is there any type of user forum or point of contacts for questions, issues, etc?

Thanks.

**Comment by niteeshbhat** [comment]
I see that the conformance test is running completely without any issues.

Can you share the MPD which creates this issue.?
Are you using this publicly deployed test page ? https://conformance.dashif.org/
or are you running it from your local machine ?

**Comment by pingu0201** [comment]
Yes, I'm using https://conformance.dashif.org/

Here's one MPD example:

<?xml version="1.0" encoding="UTF-8"?>
<MPD mediaPresentationDuration="PT491S" minBufferTime="PT10S" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 dash-mpd.xsd">
  <Period id="test_master" start="PT0S">
    <AdaptationSet codecs="avc1.4D4029" contentType="video" id="0" mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
      <SegmentTemplate duration="20020000" initialization="test_1500-Init.mp4" media="test_1500_$Number$.mp4" startNumber="1" timescale="10000000" />
      <Representation bandwidth="1500000" frameRate="30000/1001" height="720" id="test_1500" width="1280" />
    </AdaptationSet>
    <AdaptationSet codecs="mp4a.40.2" contentType="audio" id="1" lang="eng" mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1">
      <SegmentTemplate duration="9625600" initialization="test_1500-Init.mp4" media="test_1500_$Number$.mp4" startNumber="1" timescale="4800000" />
      <Representation audioSamplingRate="48000" bandwidth="160000" id="test_1500_audio0" />
    </AdaptationSet>
  </Period>
</MPD>
 
If I just select MPD conformance, it completes successfully.  So, it seems to be having problems with segment validation.

So, I then cloned and built the code on a local machine and ran ValidateMP4 on one of the .mp4 files.  I got a segmentation fault, which I traced to ValidateAtomList.cpp line 87:

vg.mir->numFragments = 0;

vg.mir is NULL here (initialized on line 69, but never set before being dereferenced)

Maybe I'm hitting this when using the web front-end?

**Comment by pingu0201** [comment]
Hmm, i pasted the MPD contents in my last update, but it didn't take.  Let me try attaching it.

[test.mpd.txt](https://github.com/Dash-Industry-Forum/Conformance-Software/files/2349362/test.mpd.txt)

**Comment by waqarz** [comment]
Without a BaseURL we cannot test it; we have no idea where the segments are

**Comment by pingu0201** [comment]
You won't be able to access the segments on our server.  Is there a way I can put them on one of your servers?  Or what's the best way to proceed?

**Comment by waqarz** [comment]
Sorry, we can only support content that is accessible. If you figure out a way to do this, please reopen this issue.
