### ISSUE TITLE
Server not responding to a basic dynamic MPD

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Software#403]
e.g. http://vm2.dashif.org/livesim/start_1800/testpic_2s/Manifest.mpd

Others may have similar issues

**Comment by niteeshbhat** [comment]
fixed here:
https://github.com/Dash-Industry-Forum/Conformance-Software/pull/404

The current period calculation had a mistake (from a very old commit). Fixed now.
