### ISSUE TITLE
SegmentBase@indexRange testing

### ISSUE THREAD

**Issue by jeremypoulter** [Dash-Industry-Forum/Conformance-Software#47]
I would like to add a test that checks that the data pointed to by the @indexRange attribute of a SegmentBase element altually points to a Segment Index Box of the correct size. Can you give me some pointers as to a good place to start?

**Comment by waqarz** [comment]
In https://github.com/Dash-Industry-Forum/Conformance-Software/commit/f2a639c6cc238ded3b83872d46a430a126e164d4
