### ISSUE TITLE
Conformance page is down on the website

### ISSUE THREAD

**Issue by richardbushell** [Dash-Industry-Forum/Conformance-Software#55]
I assume you already know, but your Conformance page is currently down on the DASH-IF website. Please put it back up asap.

**Comment by waqarz** [comment]
After restructuring of the DASH-IF site, the old code doesn't work. I am looking into ways to address this ASAP.

**Comment by waqarz** [comment]
Till this issue is resolved, please use the URL: http://54.171.149.139/test/conformancetest.php

**Comment by richardbushell** [comment]
OK, thanks. Is this temp page a slightly older version, maybe a previous backup? I note that the 'lmsg' fix you implemented last week has returned in my log.

**Comment by waqarz** [comment]
Page is back online, thanks to Akamai. Thanks for reporting.

**Comment by richardbushell** [comment]
No, it's not back yet? Just tried.

**Comment by waqarz** [comment]
This is weird, for me on some browsers (Chrome, with cache disabled) works, for some doesn't (Incognito mode, IE, Firefox). I'll ask again. For your reference again, the latest page is here: http://54.171.149.139/conformancetest.html ,  the DASH-IF URL is just a means to wrap it.

**Comment by waqarz** [comment]
Tested now, working as expected. Thanks @wilaw for the fix!
